services:
  nginx:
    image: "nginx:stable-alpine"
    restart: always
    ports:
      - "${PUBLIC_PORT}:80"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./docker/nginx/logs:/var/log/nginx"
      - "./src:/www"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: "./docker/php-fpm"
    restart: always
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${APP_VERSION}"
      APP_DEBUG: "${APP_DEBUG}"
      DATABASE_DRIVER: "${DATABASE_DRIVER}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASS: "${DATABASE_PASS}"
    volumes:
      - "./src:/www"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
    ports:
      - "${DATABASE_PORT}:5432"
